name: terceira_prova
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'  # Atualize a versão do SDK se necessário

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  floor: ^1.4.2  # Mantenha a versão 1.4.2
  floor_generator: ^1.4.2
  connectivity_plus: ^5.0.2
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.0.0
  floor_generator: ^1.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png  # Caminho para o seu ícone personalizado

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
